In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder

In [4]:
dataset = pd.read_csv("tennis.csv")
print('dataset\n',dataset)
all_col = dataset.columns
feature_cols = all_col[0:5]
print('feature_cols\n' ,feature_cols)

for label in dataset.columns:
    print(label)
    dataset[label] = LabelEncoder().fit_transform(dataset[label])

dataset
      outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no
feature_cols
 Index(['outlook', 'temp', 'humidity', 'windy', 'play'], dtype='object')
outlook
temp
humidity
windy
play


In [9]:
data = dataset.drop(['play'],axis=1)
print(data)
data = np.array(data)
print(data)

    outlook  temp  humidity  windy
0         2     1         0      0
1         2     1         0      1
2         0     1         0      0
3         1     2         0      0
4         1     0         1      0
5         1     0         1      1
6         0     0         1      1
7         2     2         0      0
8         2     0         1      0
9         1     2         1      0
10        2     2         1      1
11        0     2         0      1
12        0     1         1      0
13        1     2         0      1
[[2 1 0 0]
 [2 1 0 1]
 [0 1 0 0]
 [1 2 0 0]
 [1 0 1 0]
 [1 0 1 1]
 [0 0 1 1]
 [2 2 0 0]
 [2 0 1 0]
 [1 2 1 0]
 [2 2 1 1]
 [0 2 0 1]
 [0 1 1 0]
 [1 2 0 1]]


In [10]:
target = np.array(dataset['play'])
print('target\n',target)

target
 [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [11]:
x_train, x_test, y_train, y_test = train_test_split(data, target, test_size=0.2)

In [12]:
ID3 =DecisionTreeClassifier()
temp = ID3.fit(x_train,y_train)
print('ID3\n',temp)

ID3
 DecisionTreeClassifier()


In [13]:
y_pred = temp.predict(x_test)
print('actual\n',y_test)
print('y_pred\n',y_pred)

actual
 [0 0 0]
y_pred
 [0 1 1]


In [14]:
new_example = np.array(['sunny','hot','high','weak'])
encoded = LabelEncoder().fit_transform(new_example)
encoded = encoded.reshape(1,-1)
new_pred = temp.predict(encoded)
print('new_pred\n',new_pred)

new_pred
 [0]


In [18]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(y_pred,y_test)
acc

0.3333333333333333